all: ../../libchora.a
	#g++ util_test.cpp -o util_test -L../../ -I../../ -lchora -lSDL2 -lSDL2_image -Wall -Wextra -O -g
	#g++ intersect.cpp -o intersect -L../../ -I../../ -lchora -lSDL2 -lSDL2_image -Wall -Wextra -O -g
	g++ animacao.cpp -o animacao -L../../ -I../../ -lchora -lSDL2 -lSDL2_image -Wall -Wextra -O -g
